---
- hosts: localhost
  connection: local

  vars: 
      current_node_jt: 'jobtemplate_four'
      current_node: "{{current_node_data}}"

  tasks:
      - name: getting workflow varible from play
        debug: 
            var: current_node
        when: current_node == 'Workflow Node'

      - name: getting workflow varible from play when constion is not true
        debug: 
            var: current_node
        when: current_node == 'workflow Node'

      - debug:
          var: current_node_jt

      - name: setting varible for globle varible
        set_stats:
                  data: 
                       current_node_jt: "{{current_node_jt}}"

     