---
- hosts: localhost
  connection: local

  vars:
      current_node: 'Workflow Node'

  tasks:
        - name: displaying current node value 
          debug:
              var: current_node
        
        - name: setting the value of the varible to be access throught out the play
          set_stats:
                  data:  current_node_data: "{{current_node}}"

        - debug:
            var: current_node_data