---
- name: error handler
  hosts: localhost
  # vars_files:
  #   - vars/variables.yml

  tasks:
    - debug:
        msg: "hiiiii" 

    - debug:
        var : vcenter
        
    - debug:
        var: vcenter.in_scope|bool

    - debug:
        msg: "{{ previous_jobid }}"
      #when: previous_jobid is defined  
