---
- hosts: localhost
  gather_facts: true
  tasks:
      - debug:
          msg: "{{vcenter}}"
#searchvm
- import_playbook: error_handler.yml
  when: (vcenter.in_scope|bool) and "'search' in (vcenter.actions)"

#powerdownvm
- import_playbook: error_handler.yml
  when: (vcenter.in_scope|bool) and "'shutdown' in (vcenter.actions)"

#renamevm
- import_playbook: error_handler.yml
  when: (vcenter.in_scope|bool) and "'rename' in (vcenter.actions)"

